### ISSUE TITLE
Spaces after commas causing wrong keys definition in header mode

### ISSUE THREAD

**Issue by arfeen** [jabranr/csv-parser#17]
Consider an example having spaces after comma (usual data entry):
`name, place, thing, animal\narfeen, karachi, monitor, lion
`
These spaces will cause wrong keys in associative arrays in header mode:

```
Array
(
    [0] => Array
        (
            [name] => arfeen
            [ place] =>  karachi
            [ thing] =>  monitor
            [ animal] =>  lion
        )
)

```

Spaces should be trimmed here.

**Comment by jabranr** [comment]
@arfeen Thank you. Now in develop!
