### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by jabranr** [jabranr/csv-parser#2]

**Comment by ahmadawais** [comment]
@jabranr  You don't have a bootstrap file directing to your class. For your tests to run, you need to include the file! 

I forked the repo, and without reading what are your tests and how the class works, I think I have fixed your continuous integration issues. Although your tests are failing!

Take a look https://github.com/ahmadawais/csv-parser

Here you can see the tests are no failing https://travis-ci.org/ahmadawais/csv-parser which means CI is working.

**Comment by jabranr** [comment]
Refs: 04ac28f, dcab51d, f6efe54, 4eea195, 502a806, 0b9181f, d874531, 3e3bc07, f66deb7, a23f862, 5d9e373, 2496ed5, a718012, 2061059, 262b9eb, 3d71c10
